version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  assignees:
  - "ihs7"
  reviewers:
  - "ihs7"
  groups:
    standard-actions:
      patterns:
        - "actions/*"

- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
  assignees:
  - "ihs7"
  reviewers:
  - "ihs7"
  groups:
    eslint:
      patterns:
        - "*eslint*"
    jest:
      patterns:
        - "*jest*"