version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  assignees:
  - "ihs7"
  reviewers:
  - "ihs7"

- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
  assignees:
  - "ihs7"
  reviewers:
  - "ihs7"